version: "3.8"

services:
  user-service:
    image: ${AWS_ECR_URL}/user-service:latest
    build: ./userservice
    env_file: .env
    ports:
      - 8084:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  matchmaking-service:
    image: ${AWS_ECR_URL}/matchmaking-service:latest
    build:
      context: .
      dockerfile: elo-ranking-service/Dockerfile
    env_file: .env
    ports:
      - 8081:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  elo-ranking-service:
    image: ${AWS_ECR_URL}/elo-ranking-service:latest
    build:
      context: .
      dockerfile: elo-ranking-service/Dockerfile
    env_file: .env
    ports:
      - 8082:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  tournament-service:
    image: ${AWS_ECR_URL}/tournament-service:latest
    build: ./tournamentservice
    env_file: .env
    ports:
      - 8083:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  gateway:
    image: ${AWS_ECR_URL}/gateway-service:latest
    build: ./gateway
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: docker # Activate docker profile
    ports:
      - 8080:8080
    depends_on:
      - user-service
      - matchmaking-service
      - elo-ranking-service
      - tournament-service
    networks:
      - internal-network

  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES=user-service, tournament-service, matchmaking-service, elo-ranking-service
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/postgres-initdb.sh
    networks:
      - internal-network

volumes:
  db-data:

networks:
  internal-network:
    driver: bridge
