version: "3.8"

services:
  user-service:
    build: ./user-service

    image: vynious/user-service
    env_file: .env
    ports:
      - 8084:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  matchmaking-service:
    build: ./matchmaking-service

    image: vynious/matchmaking-service
    env_file: .env
    ports:
      - 8081:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  auth-service:
    build: ./auth-service

    image: vynious/auth-service
    env_file: .env
    ports:
      - 8085:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  elo-ranking-service:
    build: ./elo-ranking-service

    image: vynious/elo-ranking-service
    env_file: .env
    ports:
      - 8082:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  tournament-service:
    build: ./tournament-service

    image: vynious/tournament-service
    env_file: .env
    ports:
      - 8083:8080
    depends_on:
      - postgresdb
    networks:
      - internal-network

  gateway:
    build: ./gateway-service

    image: vynious/gateway-service
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Activate docker profile
    ports:
      - 8080:8080
    depends_on:
      - auth-service
      - user-service
      - matchmaking-service
      - elo-ranking-service
      - tournament-service
    networks:
      - internal-network

  postgresdb:
    image: postgres
    container_name: postgresdb
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES=$POSTGRES_MULTIPLE_DATABASES
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/postgres-initdb.sh
    networks:
      - internal-network

volumes:
  db-data:

networks:
  internal-network:
    driver: bridge