server:
  port: 8080
  servlet:
    application-display-name: gateway
spring:
  application:
    name: gateway
  security:
    basic:
      enabled: false
  cloud:
    gateway:
      routes:
        - id: elo-ranking-service
          uri: http://localhost:8082
          predicates:
            - Path=/elo-ranking/api/**  # Prefix path


        - id: matchmaking-service
          uri: http://localhost:8081
          predicates:
            - Path=/matchmaking/api/**

        - id: tournament-service
          uri: http://localhost:8083
          predicates:
            - Path=/tournament/api/** # todo

        - id: user-service
          uri: http://localhost:8084
          predicates:
            - Path=/userclan/api/**

ms:
  elo-ranking-service:
    root: http://localhost:8082
  matchmaking-service:
    root: http://localhost:8081
  tournament-service:
    root: http://localhost:8083
  user-service:
    root: http://localhost:8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
