server:
  port: 8080
  servlet:
    application-display-name: gateway
spring:
  application:
    name: gateway
  security:
    basic:
      enabled: false
  cloud:
    gateway:
      routes:
        - id: elo-ranking-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/elo-ranking/**

ms:
  elo-ranking:
    root: http://localhost:8082

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
