server:
  port: 8080
  servlet:
    application-display-name: gateway

spring:
  application:
    name: gateway
  security:
    basic:
      enabled: false

  cloud:
    gateway:
      routes:
        - id: elo-ranking-service
          uri: http://elo-ranking-service:8080  # Use Docker service name
          predicates:
            - Path=/elo-ranking/api/**

        - id: matchmaking-service
          uri: http://matchmaking-service:8080  # Use Docker service name
          predicates:
            - Path=/matchmaking/api/**

        - id: tournament-service
          uri: http://tournament-service:8080  # Use Docker service name
          predicates:
            - Path=/tournament/api/**

        - id: user-service
          uri: http://user-service:8080  # Use Docker service name
          predicates:
            - Path=/clanuser/api/**

ms:
  elo-ranking-service:
    root: http://elo-ranking-service:8080  # Docker service name
  matchmaking-service:
    root: http://matchmaking-service:8080
  tournament-service:
    root: http://tournament-service:8080
  user-service:
    root: http://user-service:8080
  auth-service:
    root: http://auth-service:8080




# todo: to update the endpoints specifically based on RBAC
route-roles:
  routes:
    "elo-ranking.api.rank.ranks.GET":
      - ROLE_ADMIN
      - ROLE_PLAYER
    "elo-ranking.api.rank.ranks.POST":
      - ROLE_ADMIN
    "elo-ranking.api.game-score.player.{playerId}.tournament.{tournamentId}.stats.GET":
      - ROLE_PLAYER
      - ROLE_ADMIN
    "clanuser.api.users.{userId}.overall.GET":
      - ROLE_PLAYER
      - ROLE_ADMIN
    "matchmaking.api.start.GET":
      - ROLE_ADMIN
      - ROLE_PLAYER
    "matchmaking.api.scheduleGames.POST":
      - ROLE_ADMIN
    "matchmaking.api.clanAvailability.bulk.POST":
      - ROLE_ADMIN
      - ROLE_CLAN_LEADER
    "matchmaking.api.clanAvailability.GET":
      - ROLE_ADMIN
      - ROLE_CLAN_LEADER
    "matchmaking.api.clanAvailability.PUT":
      - ROLE_ADMIN
      - ROLE_CLAN_LEADER
    "matchmaking.api.getSelectedPlayerEloRanks.POST":
      - ROLE_ADMIN
    "matchmaking.api.start.POST":
      - ROLE_ADMIN
    "tournament.api.details.GET":
      - ROLE_ADMIN


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    com.example.gateway: DEBUG
