name: CD Pipelines

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          DOCKERHUB_REPO: jjlim159
          POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_MULTIPLE_DATABASES: users,tournaments,matchmaking,elo-ranking
          POSTGRES_URL: jdbc:postgresql://${{ secrets.POSTGRES_HOST }}:${{ secrets.POSTGRES_PORT }}/${{ secrets.POSTGRES_DB }}
          SPRING_PROFILES_ACTIVE: docker

      - name: Move .env file to backend directory
        run: mv .env backend/.env

      - name: Downloading docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
            version: '2.14.2'

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            jjlim159/elo-ranking-service:latest
            jjlim159/tournament-service:latest
            jjlim159/matchmaking-service:latest
            jjlim159/user-service:latest
            jjlim159/auth-service:latest
            jjlim159/gateway-service:latest
            jjlim159/postgres
          context: .  # This is the default build context, you can update it if needed for different services
          file: ./Dockerfile  # Set the Dockerfile location if it's not at the root
