name: CI Pipeline

on:
  pull_request:
    branches:
      - staging
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Downloading of docker-compose
        uses: KengoTODA/actions-setup-docker-compose@v1
        with:
            version: '2.14.2'

      - name: Build and push Docker images with Docker Compose
        run: |
          docker-compose -f backend/docker-compose.yml build

